### ISSUE TITLE
When privacy mode is enabled, implement two-phase "Like" buttons 

### ISSUE THREAD

**Issue by Rudd-O** [collective/sc.social.like#79] opened 2016-09-29 23:17 UTC
Some sites offer greyed-out Like buttons that only light up and become clickable when the user first clicks on them.  Behind the scenes, a small JS script loads the corresponding social network JS that, in turn, actually enables the Like button.  This allows sites to load faster (because they do not load resources from external sites until they are strictly needed) and it also allows users of the site not to report their Web browsing activity when they visit a Web site that has these greyed-out-first buttons.

I would like it very much if this add-on implemented a toggle that enabled that feature.  If this requires funding, we can discuss it, as I'd like to use it for my site, but not without the privacy feature.

Thank you for your great work!

**Comment by hvelarde** [comment] 2016-09-30 12:51
@Rudd-O we already have a privacy option in this package that shows the buttons wihtout loading the widgets, have you tried that? see #54.

**Comment by Rudd-O** [comment] 2016-09-30 14:19
Oh, forgive me, I didn't know!   CHecking it out.

**Comment by Rudd-O** [comment] 2016-09-30 14:21
Does this package add a cookies warning?

**Comment by Rudd-O** [comment] 2016-09-30 14:26
Actually, the way this works isn't how I imagined the feature would be implemented.  If they are only rendered as links, then the user goes to a different page.  I want the buttons to appear as they usually do, but served from the Plone server and...

...actually, let me show by example what I meant:

http://thepoliticsofsystems.net/2011/09/a-two-click-like-button-for-more-privacy/

See?  This is how it works.  Simple links do not do this.  I would like that to be implemented in lieu of "simple links".  It has the same privacy properties, but works better and more like it was supposed to.

**Comment by hvelarde** [comment] 2016-09-30 16:00
take a look at the date of that post; the canonical way of implementing privacy is what we have right now; IMO, adding the behavior you want just increases the complexity of the feature and I see no real benefits on privacy.

@keul comments?

**Comment by Rudd-O** [comment] 2016-09-30 16:12
The benefits are not for privacy.  The benefits are for usability.  Clicking like without leaving the site is a better user experience.

I don't know what you mean by "works as expected" but I can tell you this: on the site you shared here, the Facebook circle doesn't do anything for me.  It is literally just an image that doesn't do anything.

**Comment by hvelarde** [comment] 2016-09-30 16:23
the title of the issue is "Implement privacy-compatible likes"; for me that means that you are concerned with privacy, and privacy is handled by using the DNT header and by not loading the widgets in the first place because they represent a privacy risk.

on the site I shared both, the Facebook and Twitter icons open a small modal that lets me share the content in both social networks; if that is not happening to you maybe we have a bug, because that's working for me.

could you please tell us what browser are you using and check you browser JavaScript console and pop-up configurations?

**Comment by Rudd-O** [comment] 2016-09-30 16:41
OK, your response to my question indicates to me that I failed to explain to you what the feature request is about.  I will compose a more detailed explanation in the following minutes.

**Comment by Rudd-O** [comment] 2016-09-30 16:51
**Current implementation**

When the browser sends the DNT header to the server, or the privacy mode is enabled, the "Like" widgets are not displayed.

Under any other circumstances, the "Like" widgets are displayed by loading "Like" assets from Facebook and Twitter that tracks the browser.

**Proposed implementation**

When the browser sends the DNT header to the server, or the privacy mode is enabled, _ersatz_ "Like" widgets are displayed.  These do not load any JS from Facebook or Twitter.  (Details of how they look, we can discuss separately.).  They will, upon hover or :active, display a tooltip that says something similar to "For your privacy, you must click this button in order to activate it first". (Details of how this is worded, we can discuss separately.)

When the user clicks on any of these _ersatz_ "Like" widgets, the ersatz widget is replaced by the corresponding social network asset that enables the "Like" feature.  At this point, the user can then click the _real_ "Like" widget, in order to actually _like_ the site on the pertinent social network.

**Advantages**

* This differs very little from the actual user experience of liking a page, and imposes little cognitive load on the user.
* It allows users, even those who have opted out of tracking by default, to still use a "Like" feature exceptionally.
* Since the widgets do show (but are greyed out), the page layout is not at risk of getting discombobulated or rearranged, so theme designers and site operators do not need to test two different versions of the same page (privacy vs. no privacy) to see if it renders differently.

**Comment by Rudd-O** [comment] 2016-09-30 17:19
Actually, upon further contemplation and reading the code, I discovered #80 and #81.  I rescind my previous offer to fund the development of this feature.  You may feel free to close the issue or never act upon it — I will be using some other solution to provide social integration in my sites.

Thanks and sorry for the bother.

**Comment by hvelarde** [comment] 2016-09-30 17:42
I think have never seen that behavior that you're proposing anywhere in the we before that post that you pasted above. having said that, I'm going to close this as it seems way to specific for a general add-on and I don't want to add complexity for some relative advantages:

* this behavior is not standard and will confuse non-power users
* users can still use the Like feature when the privacy option is enabled as I mentioned above

**Closed by hvelarde** 2016-09-30 17:42 UTC
Labels: wontfix

**Comment by keul** [comment] 2016-10-01 12:36
My 2 cents.

The behavior described by @Rudd-O is not new to me: it was used by a well know social integration JS library the time I implemented privacy feature, but as @hvelarde said, it was too complex for the current implementation (and customer budget).
