### ISSUE TITLE
Caching issues with WhatsApp button

### ISSUE THREAD

**Issue by rodfersou** [collective/sc.social.like#56] opened 2015-09-10 12:55 UTC
I know this is [already implemented to show just on mobile devices](https://github.com/collective/sc.social.like/blob/master/sc/social/like/plugins/whatsapp/browser.py#L81-L93).

But we have a plone site that is showing this button anyway because the site was accessed first on mobile device and our cache server used this generated html on every device, showing the `whatsapp` button at desktop for some pages.

The suggested fix is to remove this feature from `python` code, and implement it with `javascript`.

[This page](http://detectmobilebrowsers.com/) has an example on how to get it working with `javascript`.

**Comment by cleberjsantos** [comment] 2015-09-10 13:39
Hello @rodfersou the problem seems to be with the memoize, it's not being used properly and this is making the cache. I think using more one javascript file will leave minimally loading the plugin and, consequently, the load slowest page.

**Comment by rodfersou** [comment] 2015-09-10 14:00
@cleberjsantos we don't use memoize in this plugin

**Comment by cleberjsantos** [comment] 2015-09-10 14:08
@rodfersou yes, we use for template render ;-)

**Comment by hvelarde** [comment] 2015-09-10 14:15
@cleberjsantos if you're talking about [this memoize](https://github.com/collective/sc.social.like/blob/master/sc/social/like/browser/viewlets.py#L24) it doesn't seem to make sense at all as it's a view memoize and for me we're gaining nothing with it.

the problem is the following: we are using a moderate caching rule that caches for 15 minutes the content types views; if the first user that visits an item, is using a mobile device, the WhatsApp stuff will be in the rendering and will be cached.

by moving part of the logic outside the backend into some JS executed by the client, we will avoid that problem; that's the way all other plugins work.

**Closed** 2015-09-16 15:44 UTC
